name: Build and Publish

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dart-postgres:
        image: twosixlabsdart/dart-postgres:2.0.10
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and Test
        run: sbt test

  publish-to-docker-hub:
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and Push Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: make docker-push

  tag-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          persist-credentials: false
      - name: Tag a release
        uses: twosixlabs-dart/dart-tag-release@v3.0.20
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
